Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreAndFood.Repositories;
using Microsoft.AspNetCore.Mvc;
using CoreAndFood.Data.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;
using System.IO;

namespace CoreAndFood.Controllers
{
    public class FoodController : Controller
    {
        Context c = new Context();

        FoodRepository foodRepository = new FoodRepository();
        public IActionResult Index(int page=1)
        {        
            return View(foodRepository.TList("Category").ToPagedList(page,10));
        }

        [HttpGet]
        public IActionResult FoodAdd()
        {
            List<SelectListItem> values = (from x in c.categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();
            ViewBag.v1 = values;
            return View();
        }

        [HttpPost]
        public IActionResult FoodAdd(productAdd par)
        {
            Food f = new Food();
            if (par.ImageUrl !=null)
            {
                var extension = Path.GetExtension(par.ImageUrl.FileName);
                var newimagename = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/resimler/", newimagename);
                var stream = new FileStream(location, FileMode.Create);
                par.ImageUrl.CopyTo(stream);
                f.ImageUrl=newimagename;
            }

            f.Name = par.Name;
            f.Description = par.Description;
            f.Price = par.Price;
            f.Stock = par.Stock;
            f.CategoryID = par.CategoryID;

            foodRepository.TAdd(f);
            return RedirectToAction("Index");
        }

        public IActionResult FoodDelete(int id)
        {
            foodRepository.TDelete(new Food { FoodID = id });
            return RedirectToAction("Index");
        }

     
        public IActionResult FoodGet(int id)
        {
            var x = foodRepository.TGet(id);

            List<SelectListItem> values = (from y in c.categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.CategoryName,
                                               Value = y.CategoryID.ToString()
                                           }).ToList();
            ViewBag.v1 = values;

            Food fod = new Food()
            {
                FoodID = x.FoodID,
                Name = x.Name,
                Description = x.Description,
                Price = x.Price,
                Stock = x.Stock,
                ImageUrl = x.ImageUrl
            };
            return View(fod);
        }

        [HttpPost]
        public IActionResult FoodUpdate(Food par)
        {
            var x = foodRepository.TGet(par.FoodID);
            x.Name = par.Name;
            x.CategoryID = par.CategoryID;
            x.Description = par.Description;
            x.Price = par.Price;
            x.Stock = par.Stock;
            x.ImageUrl = par.ImageUrl;
            foodRepository.TUpdate(x);
            return RedirectToAction("Index");
        }


    }
}

Views/Food/FoodAdd.cshtml
@model CoreAndFood.Data.Models.productAdd
@{
    ViewData["Title"] = "FoodAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food Add Page</h2>
<br />
<form class="form-group" action="FoodAdd" asp-controller="Food" method="post" enctype="multipart/form-data">
    @Html.Label("Food Name")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Name, "", new { @style = "color:red" })
    <br />
    @Html.Label("Stock")
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Stock, "", new { @style = "color:red" })
    <br />

    @Html.Label("Price")
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Price, "", new { @style = "color:red" })
    <br />
    @Html.Label("Image Url")
    <input type="file" name="ImageUrl" />
    <br />
    @Html.Label("Category")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryID, "", new { @style = "color:red" })

    <br />
    @Html.Label("Description")
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Description, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-success">Save</button>
</form>

Views/Food/FoodGet.cshtml
@model CoreAndFood.Data.Models.Food
@{
    ViewData["Title"] = "FoodGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food Update Page</h2>
<br />
@using (Html.BeginForm("FoodUpdate", "Food", FormMethod.Post))
{
   
    @Html.HiddenFor(x => x.FoodID, new { @class = "form-control" })
    <br />

    @Html.Label("Food Name")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Name, "", new { @style = "color:red" })
    <br />
    @Html.Label("Stock")
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Stock, "", new { @style = "color:red" })
    <br />

    @Html.Label("Price")
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Price, "", new { @style = "color:red" })
    <br />
    @Html.Label("Image Url")
    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
    <br />
    @Html.Label("Category")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control" })

    <br />
    @Html.Label("Description")
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Description, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-info">Update</button>
}

Views/Food/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@model IPagedList<CoreAndFood.Data.Models.Food>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food List</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Food Name</th>
        <th>Category Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Delete</th>
        <th>Update</th>
        <th>Details</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.FoodID</td>
            <td>@item.Name</td>
            <td>@item.Category.CategoryName</td>
            <td>@item.Price</td>
            <td>@item.Stock</td>
            <td><a href="/Food/FoodDelete/@item.FoodID" class="btn btn-danger">Delete</a></td>
            <td><a href="/Food/FoodGet/@item.FoodID" class="btn btn-success">Update</a></td>
            <td><a href="#" class="btn btn-warning">Detail</a></td>
        </tr>
    }
</table> 
@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
<a href="/Food/FoodAdd/" class="btn btn-primary">New Food</a>