Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreAndFood.Data;
using CoreAndFood.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreAndFood.Controllers
{
    public class ChartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult VisualizeProductResult()
        {
            return Json(ProList());
        }

        public List<Class1> ProList()
        {
            List<Class1> cs = new List<Class1>();
            using (var c = new Context())
            {
                cs = c.foods.Select(x => new Class1
                {
                    foodname = x.Name,
                    price = x.Price                 
                }).ToList();
            }
            return cs;
        }

        public IActionResult Statistics()
        {
            Context c = new Context();
            var deger1 = c.foods.Count();
            ViewBag.d1 = deger1;

            var deger2 = c.categories.Count();
            ViewBag.d2 = deger2;


            var deger3 = c.foods.Where(x=>x.CategoryID== c.categories.Where(z=>z.CategoryName == "Fruit").Select(y=>y.CategoryID).FirstOrDefault()).Count();
            ViewBag.d3 = deger3;

            var deger4 = c.foods.Where(x => x.CategoryID == c.categories.Where(z => z.CategoryName == "Vegatables").Select(y => y.CategoryID).FirstOrDefault()).Count();
            ViewBag.d4 = deger4;

            var deger5 = c.foods.Where(x => x.CategoryID == c.categories.Where(z => z.CategoryName == "Legumes").Select(y => y.CategoryID).FirstOrDefault()).Count();
            ViewBag.d5 = deger5;

            var deger6 = c.foods.Sum(x=>x.Price);
            ViewBag.d6 = deger6;

            var deger7 = c.foods.OrderByDescending(x => x.Stock).Select(y=>y.Name).FirstOrDefault();
            ViewBag.d7 = deger7;

            var deger8 = c.foods.OrderBy(x => x.Stock).Select(y => y.Name)
                .FirstOrDefault();
            ViewBag.d8 = deger8;

            var deger9 = c.categories.Where(x => x.CategoryName == "Legumes").Select(y => y.CategoryID).FirstOrDefault();
            var deger9c = c.foods.Where(y => y.CategoryID == deger9).Sum(x => x.Price);
            ViewBag.d9 = deger9c;

            var deger10 = c.categories.Where(x => x.CategoryName == "Fruit").Select(y => y.CategoryID).FirstOrDefault();
            var deger10c = c.foods.Where(y => y.CategoryID == deger10).Sum(x => x.Price);
            ViewBag.d10 = deger10c;

            var deger11 = c.categories.Where(x => x.CategoryName == "Vegatables").Select(y => y.CategoryID).FirstOrDefault();
            var deger11c = c.foods.Where(y => y.CategoryID == deger11).Sum(x => x.Price);
            ViewBag.d11 = deger11c;

            var deger12 = c.foods.OrderByDescending(x => x.Price).Select(y => y.Name).FirstOrDefault();
            ViewBag.d12 = deger12;

            return View();
        }
    }
}

Views/Chart/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Fiyatlar');               
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.foodname, obj.price]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Food - Price Grafiği",
                width: 1000,
                height: 700,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

Views/Chart/Statistics.cshtml
@{
    ViewData["Title"] = "Statistics";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    ViewData["Title"] = "Deneme";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="~/web2/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />

    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>
    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.d1</h3>
                    <p>Total Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">
                <div class="icon-text">
                    <h3>@ViewBag.d2</h3>
                    <p>Total Category</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">
                <div class="icon-text">
                    <h3>@ViewBag.d3</h3>
                    <p>Fruit Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">
                <div class="icon-text">
                    <h3>@ViewBag.d4</h3>
                    <p>Vegatable Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f39c12">
                <div class="icon-text">
                    <h3>@ViewBag.d5</h3>
                    <p>Legaumes Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#d35400">
                <div class="icon-text">
                    <h3>@ViewBag.d6</h3>
                    <p>Sum Food Price</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#c0392b">
                <div class="icon-text">
                    <h3>@ViewBag.d7</h3>
                    <p>Food Max Stock</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#7f8c8d">
                <div class="icon-text">
                    <h3>@ViewBag.d8</h3>
                    <p>Food Min Stock</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.d10</h3>
                    <p>Sum Fruit</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">
                <div class="icon-text">
                    <h3>@ViewBag.d11</h3>
                    <p>Sum Vegatables</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">
                <div class="icon-text">
                    <h3>@ViewBag.d9</h3>
                    <p>Sum Legumes</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">
                <div class="icon-text">
                    <h3>@ViewBag.d12</h3>
                    <p>Max Price Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>

</body>
</html>